#!/bin/sh

### BEGIN INIT INFO
# Provides:          atlassian-ip-range-fw-cfg
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Atlassian IP Range Firewalld configurator
# Description:       Generates a firewalld zone xml configuration providing access to ssh from bitbucket pipelines, and reloads firewalld.
### END INIT INFO

set -e
set -u

# Prints an error message and exits the script with a non-zero exit code.
error_exit() {
  echo "Error: $1" >&2
  exit 1
}

# Fetch the JSON file containing the IP ranges for Atlassian products
JSON_FILE=$(mktemp)
curl -s -f https://ip-ranges.atlassian.com > "$JSON_FILE" || error_exit "Failed to fetch IP ranges from Atlassian server"

# create empty zone xml file
cat << EOF > /etc/firewalld/zones/bitbucket.xml
<?xml version="1.0" encoding="utf-8"?>
<zone target="ACCEPT">
  <short>Trusted</short>
  <description>All SSH connections from BitBucket are accepted.</description>
  <service name="ssh"/>
</zone>
EOF

# Extract the IP addresses for Bitbucket from the JSON file
IP_ADDRESSES=$(grep "cidr" "$JSON_FILE" | awk -F\" '{print $4}')

# Add ip addresses to the bitbucket.xml zone file
for IP_ADDRESS in $IP_ADDRESSES
do
sed -i '/description/a  \<source address=\"'"$IP_ADDRESS"'\"\/\>' /etc/firewalld/zones/bitbucket.xml;
done

# reload firewall
systemctl reload firewalld

# Clean up
rm "$JSON_FILE"

exit 0